### ISSUE TITLE
info for bind_dns_keys

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#142]
I have 2 server, master and slave (now primary and secondary):

into playbook this vars is auto-gen the key or no?
i don't think i have to manually generate a key for each domain.

thanks

**Comment by GR360RY** [comment]
The bind_dns_keys definition is configured per server (or group of servers) and per zone. You need to setup it once per server or per group of servers.

bind_dns_keys variable is an empty list by default (we are not generating it): you need to configure it either in inventory or in playbook vars section. See examples below:

```yaml
- hosts: dns_servers
  
  vars:
    bind_dns_keys:
      - name: primary_key
        algorithm: hmac-sha256
        secret: "azertyAZERTY123456"
    bind_zones:
      - name: 'example.com'
         primaries:
           - 10.11.0.1
         ....
    
    roles:
      - bertvv.bind
```
