### ISSUE TITLE
record txt

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#145]
hi, how to insert record spf, dmarc etc?
Thanks.

**Comment by GR360RY** [comment]
Checkout out the molecule scenario with examples [molecule/default/host_vars/ns1.yml](../blob/master/molecule/default/host_vars/ns1.yml):

```yaml
    text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
      - name: '@'
        text:
          - 'some text'
          - 'more text'
```
