### ISSUE TITLE
String dkim

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#149]
i have this key:
```bash
mail._domainkey	IN	TXT	( "v=DKIM1; h=sha256; k=rsa; "
	  "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA109hqnCo/UuXhiw/vp36rVci2n/5MKi+5ZMidWJf4w9DcEB9VG7H23+9XyQ6UFs/hRaFntdeX9GB1UFBSS0C3Gg/pL88As
CzBMDCXmPKUU4eEiK4YV+uc59jBLZnEA8ONDT5xSG6+ZDtl8diaKdMQH9kQAN3uLS/HvqbCPRqVwlaqeRKJ2UenJW2Cmvc3094Jpvcyp1sD9LUpw"
	  "RMgclxHzWwhLln/NHbYaw7mjVkkWN32MxJCeHLslHn8pLRcadJ5gk82K+1IuHEJ+LZRIUfy5gzKtQJyez0rTiOLp1gesvXmbOosSMKRjr7BklxWPfzPWtqyPqRPKi83qXNfIfpuQIDAQ
AB" )  ;
```

i insert: 
```yml
    text:
      - name: 'mail._domainkey'
        text: 'v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA109hqnCo/UuXhiw/vp36rVci2n/5MKi+5ZMidWJf4w9DcEB9VG7H23+9XyQ6UFs/hRaFntdeX9GB1UFBSS0C3Gg/pL88AsCzBMDCXmPKUU4eEiK4YV+uc59jBLZnEA8ONDT5xSG6+ZDtl8diaKdMQH9kQAN3uLS/HvqbCPRqVwlaqeRKJ2UenJW2Cmvc3094Jpvcyp1sD9LUpw RMgclxHzWwhLln/NHbYaw7mjVkkWN32MxJCeHLslHn8pLRcadJ5gk82K+1IuHEJ+LZRIUfy5gzKtQJyez0rTiOLp1gesvXmbOosSMKRjr7BklxWPfzPWtqyPqRPKi83qXNfIfpuQIDAQAB'
```

don't write file on server, because?
Thanks.
