### ISSUE TITLE
Same reverse (networks) for differents bind_zones

### ISSUE THREAD

**Issue by roumano** [bertvv/ansible-role-bind#171]
Hi,

Actually the role is not working for same reverse (networks) for differents zone
Like this simplified exemple : 
```
bind_zones:
- name: domain1.fr
  networks:
  - '127.0.0'
  - '127.0.1'
- name: domain2.fr
- name: domain3.fr
  networks:
  - '127.0.0'
  - '127.0.1'
- name: domain4.fr
  networks:
  - '127.0.3'
```

It's creating 2 different issues :
- Duplicate reverse zone entry in /etc/bind/named.conf
I already have a fix for this.
- few tasks use  sub_elements like this :
```
 with_subelements:
    - "{{ bind_zones }}"
    - networks
    - flags:
      skip_missing: true
```
As it's create unwanted loop iteration (it's erasing first data of the loop), reserve zone are badly created.
To fix it properly, i think it's should first create a dict or reverse zone like this : 
```
reverse:
- name: 127.0.0
  domaine:
  - domain1.fr
  - domain3.fr
- name: 127.0.1
  domaine:
  - domain1.fr
  - domain3.fr
- name: 127.0.3
  domaine:
  - domain4.fr
```
Do you known, how it's can be done ?
