### ISSUE TITLE
 Create forward lookup zone file: AnsibleUndefinedVariable: 'dict object' has no attribute 'serial'

### ISSUE THREAD

**Issue by ruan-dt** [bertvv/ansible-role-bind#183]
Short error output:
``` yaml
TASK [bertvv.bind : Create forward lookup zone file] ***************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'serial'
failed: [hostname] (item=domain.name) => {"ansible_loop_var": "item", "changed": false, "item": {"create_reverse_zones": true, "hosts": [{"aliases": ["a1", "a2", "a3"], "ip": "172.20.8.1", "name": "gateway"}, {"aliases": ["b1"], "name": "somewhere.else."}], "name": "domain.name", "name_servers": ["gateway.domain.name."], "primaries": ["172.20.8.1"], "type": "primary"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'serial'"}
```

Running with `-vvv` didn't obviously turn up anything more useful, but I can add that output if needs be.

Is this me doing something wrong? Having only been using ansible for a few weeks, and lacking supervision, I can't really tell myself.

**Comment by blofeldthefish** [comment]
Hi @ruan-dt 

Can you provide the playbook you were using with this role, and it will provide more insight as to what your particular issue is.

We can then look at closer....

**Comment by ruan-dt** [comment]
@blofeldthefish so, finally having a little time to get back to this again:
 - the target machines are running ubuntu 22.04
 - tested on two different controllers, one running ubuntu 18.04 lts and one running ubuntu 20.04 lts
 - the playbook completes absolutely fine if only one host is targeted.
 - where two hosts are targeted, it completes only for the first host, with the second host showing the `has no attribute 'serial'` error.

Minimal host file:

```
host0 field_subnet="172.20.4.0/22"
host1 field_subnet="172.20.8.0/22"
```

Minimal playbook:

``` yaml
- name: configure hosts
  hosts:
   - host0
   - host1

  vars:
    field_ip: "{{ field_subnet | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr('1') | ansible.netcommon.ipaddr('address') }}"

  roles:
    - role: bertvv.bind
      become: yes

      # if this is missing, the version of bind on ubuntu 22.04 will raise a grumpy 
      # "option 'dnssec-enable' no longer exists" error.
      bind_dnssec_enable: false

      bind_zones:
        - name: "{{ site_name }}"
          type: primary
          primaries:
            - "{{ field_ip }}"
          name_servers:
            - "gateway."
          hosts:
            - name: gateway
              ip: "{{ field_ip }}"
```

**Comment by patrickstump** [comment]
Can confirm this issue. It appears to manifest when running against more than one server. For example is `hosts: group_name` vs `hosts: server.domain.name`.
The issues is that serial is only calculated as a `run_once` at [tasks/main.yml line 78](https://github.com/bertvv/ansible-role-bind/blob/bc9e234d4f167c02be83538671377e42f2b86b88/tasks/main.yml#L78).

```yaml
- name: Create serial, based on UTC UNIX time
  command: date -u +%s
  register: timestamp
  changed_when: false
  run_once: true
  check_mode: false
  tags: bind
```

When running against one host, the serial is created for that host. When running for more than one host, that variable is only registered for the first host, but referenced in every host. Thus causing the undefined variable.
