### ISSUE TITLE
Fatal: msg: The ipaddr filter requires python's netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#197]
```
ASK [bind : Read reverse ipv6 zone hashes] *********************************************************************************************************************************************************************************************
Friday 02 September 2022  15:21:00 +0200 (0:00:00.560)       0:01:14.006 ****** 
[DEPRECATION WARNING]: Use 'ansible.utils.ipaddr' module instead. This feature will be removed from ansible.netcommon in a release after 2024-01-01. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
fatal: [ns1-basilicata.ninux.org]: FAILED! => 
  msg: The ipaddr filter requires python's netaddr be installed on the ansible controller

```
in my playbook i have this pre-task:
```
  pre_tasks:
    - name: Install python3-netaddr
      apt: pkg=python3-netaddr state=present
    - name: Install python3-ipaddr
      apt: pkg=python3-ipaddr state=present
    - name: Install python3-dns
      apt: pkg=python3-dns state=present
    - name: Install dns utils
      apt: pkg=dnsutils state=present
    - name: Install dns certbot
      apt: pkg=python3-certbot-dns-rfc2136 state=present
    - name: Get dict for each zone
      include_vars:
        dir: zones
    - name: Merge zone dicts
      set_fact:
        bind_zones:
          "{{ nnxx_ninux_org }} +
           {{ basilicata_ninux_org }} +
           {{ basilicata_nnxx }}"
```
