### ISSUE TITLE
Reverse zones are not generated for hosts with multiple ips

### ISSUE THREAD

**Issue by mikelsid** [bertvv/ansible-role-bind#209]
Currently if ip for host is specified as list, PTR records are not generated
For example:
``` yaml
    hosts:
      - name: dns-01
        ip:
          - "10.0.0.2"
      - name:  test
        ip: 
          - "10.0.0.3"
          - "10.0.0.4"
```
Such hosts won't receive any PTR records
