### ISSUE TITLE
bind_zone_hosts from inventory

### ISSUE THREAD

**Issue by aido** [bertvv/ansible-role-bind#45]
Hi,

Is it possible to populate the `bind_zone_hosts` variable with values from the inventory?

The following in `group_vars` reports an error `'item' is undefined`
```yaml
bind_zone_hosts:
  - name: "{{ item }}"
    ip: "{{ hostvars['{{ item }}']['ansible_host'] }}"
    with_items: "{{ groups['all'] }}"
```

**Comment by bertvv** [comment]
I don't think `with_items` works like that. That can only be used in a task, not in a variable.

I like the suggestion, but I don't expect to be able to implement this any time soon. It's also more complex than you would think at first, given the current implementation of the role.

If you want a quick-and-dirty solution, you could combine my `bertvv.hosts` role (that populates /etc/hosts file with Ansible managed hosts) with `bertvv.dnsmasq`.

- <https://github.com/bertvv/ansible-role-hosts>
- <https://github.com/bertvv/ansible-dnsmasq>

I'm going to close this issue, as I have no plans to work on this feature in the foreseeable future.

**Comment by flickerfly** [comment]
@aido did you come up with a solution? I'm going to be trying this when I can get to my environment.

```
  tasks:
    - name: Create node_hosts variable
      set_facts:
        node_hosts:
          - name: "{{ hostvars[item]['inventory_hostname'] }}"
            ip: "{{ hostvars[item]['ansible_host'] }}"
      with_items:: groups['nodes']

    - name: Create master_hosts variable
      set_facts:
        master_hosts:
          - name: "{{ hostvars[item]['inventory_hostname'] }}"
            ip: "{{ hostvars[item]['ansible_host'] }}"
        with_items: groups['masters']

    - name: Add nodes and masters to bind hosts variable
      set_facts:
        hosts: "{{ hosts + node_hosts + master_hosts }}"
```
