### ISSUE TITLE
error: no filter named 'reverse_lookup_zone'

### ISSUE THREAD

**Issue by setkeh** [bertvv/ansible-role-bind#5]
Hi,

Thanks for the work you put into this Ansible playbook :D.

But im running into an issue trying to use it with the Vagrant ansible provisioner the output is as follows

```
==> ns1: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ns1]

TASK: [bertvv.bind | Install BIND] ******************************************** 
changed: [ns1] => (item=bind,bind-utils)

TASK: [bertvv.bind | Create serial] ******************************************* 
changed: [ns1]

TASK: [bertvv.bind | Main BIND config file (master)] ************************** 
skipping: [ns1]

TASK: [bertvv.bind | Create forward lookup zone file] ************************* 
skipping: [ns1]

TASK: [bertvv.bind | Create reverse lookup zone file] ************************* 
skipping: [ns1] => (item=192.168.1)
skipping: [ns1] => (item=10.0)

TASK: [bertvv.bind | Main BIND config file (slave)] *************************** 
fatal: [ns1] => {'msg': "AnsibleError: file: /vms/Ansible/ansible/bertvv.bind/templates/slave_etc_named.conf.j2, line number: 64, error: no filter named 'reverse_lookup_zone'", 'failed': True}
fatal: [ns1] => {'msg': "AnsibleError: file: /vms/Ansible/ansible/bertvv.bind/templates/slave_etc_named.conf.j2, line number: 64, error: no filter named 'reverse_lookup_zone'", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/bind.retry

ns1                        : ok=4    changed=2    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

My Vagrantfile is as follows,

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "ns1" do |ns1|
    ns1.vm.box = "relativkreativ/centos-7-minimal"
    ns1.vm.hostname = "ns1.setkeh.local"
    ns1.vm.network "private_network", ip: "192.168.33.10"
    ns1.vm.network "public_network", bridge: "bond0"
    ns1.vm.synced_folder "./ansible", "/ansible"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/bind.yml"
    end
  end

  config.vm.define "ns2" do |ns2|
    ns2.vm.box = "relativkreativ/centos-7-minimal"
    ns2.vm.hostname = "ns2.setkeh.local"
    ns2.vm.network "private_network", ip: "192.168.33.11"
    ns2.vm.network "public_network", bridge: "bond0"
    ns2.vm.synced_folder "./ansible", "/ansible"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/bind.yml"
    end
  end
end
```

and my bind.yml is as follows.

```
---
- hosts: all
  sudo: true
  vars:
    bind_listen_ipv4:
      - 'any'
    bind_listen_ipv6:
      - 'any'
    bind_allow_query:
      - '192.168.1.0/24'
      - '10.0.0.0/24'
    bind_zone_name: 'setkeh.local'
    bind_zone_networks:
      - '192.168.1'
      - '10.0'
    bind_zone_master_server_ip: '10.0.0.35'
    bind_zone_name_servers:
      - 'ns1'
      - 'ns2'
    bind_zone_mail_servers:
      - name: 'mail'
        preference: '10'
    bind_zone_hosts:
      - name: 'ns1'
        ip: '10.0.0.35'
        aliases:
          - ns1
      - name: 'ns2'
        ip: '10.0.0.36'
        aliases:
          - ns2
      - name: 'web'
        ip: '10.0.0.7'
        aliases:
          - www
  roles:
    - bertvv.bind
```

If you have any suggestions or idea's as to what i have misconfigured that would be greatly appreciated :)

Thanks.
