### ISSUE TITLE
error: zone has no A address records

### ISSUE THREAD

**Issue by hellt** [bertvv/ansible-role-bind#58]
Hi, thanks for this awesome role!

I have an issue where a simple zone couldn't be created because of a strange error I see. Thats my playbook:

```yaml
---
- hosts: all
  become: true
  vars:
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_zone_master_server_ip: 10.99.99.8
    bind_zone_domains:
      - name: 'nuage.internet'
        networks:
          - '10.99.99'
        name_servers:
          - ns1.nuage.internet.
        hosts:
          - name: utility
            ip: 10.99.99.8
            alias:
              - dns
          - name: vsc1
            ip: 10.99.99.4
          - name: vsc1
            ip: 10.99.99.5
          - name: vsc1
            ip: 10.99.99.6
          - name: vsc1
            ip: 10.99.99.7
  roles:
    - ansible-role-bind
```

The error is:
```
"stdout": "zone nuage.internet/IN: NS 'ns1.nuage.internet' has no address records (A or AAAA)
zone nuage.internet/IN: not loaded due to errors."
```

I am a bit lost, why cant I use 
```
 name_servers:
          - ns1.nuage.internet.
```
as my SOA? If I change this line to, say, `acme.local.` everything works, but is it a correct behavior?

**Comment by hellt** [comment]
ok, seems like I needed to explicitly A record for it
```
    bind_zone_domains:
      - name: 'nuage.internet'
        networks:
          - '10.99.99'
        name_servers:
          - ns1.nuage.internet.
        hosts:
          - name: utility
            ip: 10.99.99.8
            alias:
              - dns
          - name: ns1
            ip: 10.99.99.8
          - name: vsc1
            ip: 10.99.99.4
          - name: vsc1
            ip: 10.99.99.5
          - name: vsc1
            ip: 10.99.99.6
          - name: vsc1
            ip: 10.99.99.7
```
