### ISSUE TITLE
support multiple zones

### ISSUE THREAD

**Issue by kostyrev** [bertvv/ansible-role-bind#6]
I really like this role but its usage is kinda limited.

**Comment by bertvv** [comment]
Thank you for your feedback. I agree. However, the time I have to work on new features is very limited, so I cannot promise to ship an implementation soon. Thanks for your understanding.

PRs welcome, though!

**Comment by kostyrevaa** [comment]
Yeah. I write ansible roles too. So I feel your pain.
But I've already forked another role to tailor for my needs.

**Comment by blofeldthefish** [comment]
The most difficult part of this would be to define how to specify multiple zones in the playbook.  Having looked at some other roles, I feel that this one has the most logical and flexible definition of hosts and other record types, which are specified by the bind_zone_hosts list.   

Perhaps this could be adjusted something like:

     bind_zone_hosts
       - domain: domain1
          - name: host1
            ip: 1.2.3.4
          - name: host2
            ip: 4.5.6.7
       - domain: domain2
          - name: host1
            ip: 8.7.6.5
          - name: host2
            ip: 4.3.2.1
    
Of course bind_zone_name_servers would also likely need similar treatment.  See attached file, for a slightly tweaked snippet of the test case for this role, with a possible means of moving forward.

If we could get an open discussion of how to define all hosts / zones in a concise, flexible manner within a playbook, I am happy to assist with looking at re-working this role to offer multiple zones, and be more flexible....

[multi-zone-sample.txt](https://github.com/bertvv/ansible-role-bind/files/1122301/multi-zone-sample.txt)

**Comment by bertvv** [comment]
Indeed, a good syntax for defining the domains is one of the things keeping me from starting to work on this. Apart from the complexity and my limited time, that is...

I was thinking along these lines:

```Yaml
bind_zone_domains:
  - name: example.com
    networks:
      - "192.0.2"
      - "10"
    name_servers:
      - ns1
      - ns2
    [...]
    hosts:
      - name: host1
        ip: 192.0.2.1
      - name: host2
        ip: 10.0.0.5
  - name: acme.com
    [...]
```

Basically, all variables that now start with `bind_zone_` become fields in a dict defining a domain.

Thanks for offering your help, I think I'll need it to get this working. Especially after your awesome method of making zone file generation idempotent... ;-)
