### ISSUE TITLE
Error when role is skipped by playbook

### ISSUE THREAD

**Issue by m4dm4rtig4n** [bertvv/ansible-role-bind#68]
Hi,

When i skip role in my playbook, your role return an error :/

For fix, just add `- skip: true` in main.yml : 
```
- name: Source specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - skip: true
  tags: bind
```

EDIT : Or not with `- skip: true`, include_vars its always skipped....
