### ISSUE TITLE
Add 'dnssec-keygen' for domain

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#78]
basic script.
```
#!/bin/bash
mkdir -p /etc/bind/keys/
domain=test.loc
keyfile=/etc/bind/keys/$domain.key

if [ "x$bind_key" = x ]
then
  pushd /etc/bind/keys
  rm -f /etc/bind/keys/K$domain*
  dnssec-keygen -a HMAC-MD5 -b 512 -n HOST $domain.key
  bind_key="$(grep Key: K$domain*.private | cut -d ' ' -f 2)"
  popd
fi
chown root:bind /etc/bind/keys/K$domain*
chmod 640 /etc/bind/keys/K$domain*
```

how can it be integrated into the playbook to achieve this result?

```
key "test.loc.key" {
  algorithm hmac-md5;
  secret "WkTF9DYyK4hcboNK1cxHTK/WcFu7di/sdHkwrFJqKBJU YA+08otWNW31g==";
};

zone "test.loc" {
  type master;
  file "test.loc.zone";
  allow-query { any; };
  allow-transfer { none; };
  allow-update { key test.loc.key; };
};
```

**Comment by bertvv** [comment]
Initial implementation, genrates the .key and .private files and collects the keys:

```yaml
# tasks/dnssec-keygen.yml
# Generate DNSSEC key, inspired by Michele Salerno (@mikysal78)
---

- name: DNSSEC keygen | Ensure keys directory is present
  file:
    path: "{{ bind_dnssec_key_dir }}"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0750'
  tags:
    - bind
    - dnssec_keygen

- name: DNSSEC keygen | Create key file for each zone (This may take a long time)
  shell: >
    dnssec-keygen -a HMAC-MD5 -b 512 -n HOST "{{ item.name }}"
  args:
    chdir: "{{ bind_dnssec_key_dir }}"
    creates:
      - "K{{ item.name }}.+[0-9][0-9][0-9].+[0-9][0-9][0-9][0-9][0-9].key"
      - "K{{ item.name }}.+[0-9][0-9][0-9].+[0-9][0-9][0-9][0-9][0-9].private"
  with_items:
    - "{{ bind_zone_domains }}"
  tags:
    - bind
    - dnssec_keygen

- name: DNSSEC keygen | Ensure proper permissions on DNSSEC keys
  file:
    path: "{{ item }}"
    mode: '0640'
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
  with_fileglob:
    - "{{ bind_dnssec_key_dir }}/K*.{key,private}"
  tags:
    - bind
    - dnssec_keygen

- name: DNSSEC keygen | Gather keys from key files
  shell: >
    set -o nounset -o pipefail -o errexit &&
    grep 'Key:' "{{ bind_dnssec_key_dir }}/K{{ item.name }}".*.private | cut -d ' ' -f 2
  args:
    executable: /bin/bash
  with_items: "{{ bind_zone_domains }}"
  register:
    bind_dnssec_keys
  tags:
    - bind
    - dnssec_keygen

- name: DNSSEC keygen | Show keys (debug)
  debug:
    var: bind_dnssec_keys

```

Generating the configuration remains to be implemented.
